import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

export function parseSemver(input) {
  const match = String(input).match(/^(\d+)\.(\d+)\.(\d+)/)
  if (!match) return null
  return { major: +match[1], minor: +match[2], patch: +match[3] }
}

export function readCurrentVersion(root) {
  const pkgPath = join(root, 'package.json')
  const versionPath = join(root, 'version.build.json')

  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
    if (pkg.version) {
      const parsed = parseSemver(pkg.version)
      if (parsed) return { semver: pkg.version, ...parsed }
    }
  } catch {
    /* fall through */
  }

  try {
    const data = JSON.parse(readFileSync(versionPath, 'utf8'))
    if (data.semver) {
      const parsed = parseSemver(data.semver)
      if (parsed) return { semver: data.semver, ...parsed }
    }
    // Legacy date/build stamp — map to 1.0.0 baseline on first semver migration
    if (data.date != null && data.build != null) {
      return { semver: '1.0.0', major: 1, minor: 0, patch: 0 }
    }
  } catch {
    /* fall through */
  }

  return { semver: '1.0.0', major: 1, minor: 0, patch: 0 }
}

export function bumpSemver(current, kind) {
  const { major, minor, patch } = current
  if (kind === 'major') return { major: major + 1, minor: 0, patch: 0 }
  if (kind === 'minor') return { major, minor: minor + 1, patch: 0 }
  return { major, minor, patch: patch + 1 }
}

export function writeVersionFiles(root, semver, generatorLabel = 'scripts/bump-version.mjs') {
  const pkgPath = join(root, 'package.json')
  const versionPath = join(root, 'version.build.json')
  const outTs = join(root, 'src', 'generated', 'buildVersion.ts')
  const label = `v${semver}`

  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
  pkg.version = semver
  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`)

  writeFileSync(versionPath, `${JSON.stringify({ semver }, null, 2)}\n`)

  mkdirSync(dirname(outTs), { recursive: true })
  writeFileSync(
    outTs,
    `/** Generated by ${generatorLabel} — do not edit */\nexport const BUILD_VERSION_LABEL = '${label}'\nexport const BUILD_VERSION: { semver: string } = ${JSON.stringify({ semver })}\n`,
  )

  return label
}

export function bumpAndWriteVersion(root, kind, generatorLabel) {
  const current = readCurrentVersion(root)
  const nextParts = bumpSemver(current, kind)
  const nextSemver = `${nextParts.major}.${nextParts.minor}.${nextParts.patch}`
  const label = writeVersionFiles(root, nextSemver, generatorLabel)
  return { from: current.semver, to: nextSemver, label }
}
