import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

/** Patch component rolls to the next minor after 99 (1.13.99 → 1.14.0). */
export const SEMVER_PATCH_MAX = 99

export function parseSemver(input) {
  const match = String(input).match(/^(\d+)\.(\d+)\.(\d+)/)
  if (!match) return null
  return { major: +match[1], minor: +match[2], patch: +match[3] }
}

/** Carry patch overflow into minor (and minor into major if needed). */
export function normalizeSemverParts({ major, minor, patch }) {
  let maj = major
  let min = minor
  let pat = patch
  while (pat > SEMVER_PATCH_MAX) {
    pat -= SEMVER_PATCH_MAX + 1
    min += 1
  }
  while (min > SEMVER_PATCH_MAX) {
    min -= SEMVER_PATCH_MAX + 1
    maj += 1
  }
  return { major: maj, minor: min, patch: pat }
}

export function formatSemver({ major, minor, patch }) {
  return `${major}.${minor}.${patch}`
}

export function readCurrentVersion(root) {
  const pkgPath = join(root, 'package.json')
  const versionPath = join(root, 'version.build.json')

  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
    if (pkg.version) {
      const parsed = parseSemver(pkg.version)
      if (parsed) {
        const normalized = normalizeSemverParts(parsed)
        return { semver: formatSemver(normalized), ...normalized }
      }
    }
  } catch {
    /* fall through */
  }

  try {
    const data = JSON.parse(readFileSync(versionPath, 'utf8'))
    if (data.semver) {
      const parsed = parseSemver(data.semver)
      if (parsed) {
        const normalized = normalizeSemverParts(parsed)
        return { semver: formatSemver(normalized), ...normalized }
      }
    }
    // Legacy date/build stamp — map to 1.0.0 baseline on first semver migration
    if (data.date != null && data.build != null) {
      return { semver: '1.0.0', major: 1, minor: 0, patch: 0 }
    }
  } catch {
    /* fall through */
  }

  return { semver: '1.0.0', major: 1, minor: 0, patch: 0 }
}

export function bumpSemver(current, kind) {
  const { major, minor, patch } = normalizeSemverParts(current)
  if (kind === 'major') return { major: major + 1, minor: 0, patch: 0 }
  if (kind === 'minor') return { major, minor: minor + 1, patch: 0 }
  // Patch bump: 1.13.99 → 1.14.0
  if (patch >= SEMVER_PATCH_MAX) {
    return normalizeSemverParts({ major, minor: minor + 1, patch: 0 })
  }
  return { major, minor, patch: patch + 1 }
}

export function writeVersionFiles(root, semver, generatorLabel = 'scripts/bump-version.mjs') {
  const pkgPath = join(root, 'package.json')
  const versionPath = join(root, 'version.build.json')
  const outTs = join(root, 'src', 'generated', 'buildVersion.ts')
  const parsed = parseSemver(semver)
  const normalized = parsed ? formatSemver(normalizeSemverParts(parsed)) : semver
  const label = `v${normalized}`

  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
  pkg.version = normalized
  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`)

  let versionData = { semver: normalized }
  try {
    versionData = { ...JSON.parse(readFileSync(versionPath, 'utf8')), semver: normalized }
  } catch {
    /* new file */
  }
  writeFileSync(versionPath, `${JSON.stringify(versionData, null, 2)}\n`)

  mkdirSync(dirname(outTs), { recursive: true })
  writeFileSync(
    outTs,
    [
      `/** Generated by ${generatorLabel} - do not edit */`,
      `export const BUILD_VERSION_LABEL = '${label}'`,
      `export const BUILD_VERSION: { semver: string } = ${JSON.stringify({ semver: normalized })}`,
      '',
    ].join('\n'),
  )

  return label
}

export function bumpAndWriteVersion(root, kind, generatorLabel) {
  const current = readCurrentVersion(root)
  const nextParts = bumpSemver(current, kind)
  const nextSemver = formatSemver(nextParts)
  const label = writeVersionFiles(root, nextSemver, generatorLabel)
  return { from: current.semver, to: nextSemver, label }
}
